### ISSUE TITLE
Change dates format regex

### ISSUE THREAD

**Issue by ngchrbn** [ngchrbn/Dates-Detection#2]
Assume that the days range from 01 to 31, the months range from 01
to 12, and the years range from 1000 to 2999. 
⚠ **Note that if the day or month is a single digit, it’ll have a leading zero.**

Date is in format  **DD/MM/YYYY**

**Comment by mike-Ira** [comment]
:+1: Great
For the fourth date format, it means that it is for example ***April 20, 2020***, right?

**Comment by ngchrbn** [comment]
👌Exactly
for the abbreviations like **Apr, Dec, etc**...it will added after

**Comment by mike-Ira** [comment]
:ok: 
I'm on it

**Comment by ngchrbn** [comment]
Remember to modify the **dates_file.txt** and test it with the new dates format!

**Comment by mike-Ira** [comment]
:ok_hand:
